
---
title: "Vaccines - Check Box"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
    social: menu

runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(flexdashboard)
library(tidyverse)
library(plotly)
library(knitr)
library(DT)
library(lubridate)
df <- read_csv('https://bryantstats.github.io/math421/data/us-states.csv')

```

{.sidebar}
=======================================================================

- This dataset shows amount of cases and deaths per state in the United States of America. 

```{r}
dateRangeInput(inputId = "date_input", 
               label = h2("Date range"), 
               start = min(df$date), 
               end = max(df$date),
               min = min(df$date), 
               max = max(df$date))
```

Main Tab 1
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

### Density Plot

```{r}
renderPlotly({
  p1 <- df %>% 
    filter(date > input$date_input[1], date < input$date_input[2]) %>% 
    filter(state=='Rhode Island') %>%
    ggplot(aes(x=date, y=cases))+
    geom_point()
  ggplotly(p1)
})
```

Column {data-width=500}
-----------------------------------------------------------------------

### Bar Plot

```{r}
renderPlotly({
  p2 <- df %>% 
    filter(date > input$date_input[1], date < input$date_input[2]) %>% 
    filter(state %in% c('Rhode Island', 'Massachusetts', 'Washington')) %>% 
    group_by(state) %>%
    summarise(total_deaths = sum(deaths)) %>%
    ggplot(aes(x=state, y=total_deaths))+
    geom_col()
  ggplotly(p2)
})
```
